name: Ecr Deploy Aws

on:
  push:
    branches:
      - main
    paths:
      - 'infra/metabase-ecr/**'

jobs:
  ecr_deploy:
    name: Deploy Ecr 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: |
        terraform -chdir=infra/metabase-ecr fmt
        terraform -chdir=infra/metabase-ecr init -upgrade

    - name: Terraform Apply
      run: terraform -chdir=infra/metabase-ecr apply -auto-approve