name: Build and Deploy ECS

on:
  push:
    branches: [ "main" ]

env:
  CONTAINER_NAME: 561531741486.dkr.ecr.us-east-1.amazonaws.com/ecr-desafio-sre

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $CONTAINER_NAME:$IMAGE_TAG .
        docker image tag $CONTAINER_NAME:$IMAGE_TAG $CONTAINER_NAME:latest
        docker push $CONTAINER_NAME:$IMAGE_TAG
        docker push $CONTAINER_NAME:latest
        echo "image=$CONTAINER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

